name: Generate Snake

# Controls when the action will run
on:
  schedule:
    # Run every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:  # Allows manual trigger from the Actions tab
  push:
    branches:
      - main  # Run on push to the main branch

jobs:
  build:
    # The type of runner to use for the job
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Ensure using your custom PAT (TokenForWorkflow)

      # Step 2: Generate the snake files in './dist/'
      - name: Generate the snake files in './dist/'
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.TokenForWorkflow }}  # Use your custom token

      # Step 3: Show the build status
      - name: Show build status
        run: git status

      # Step 4: Push new files to the output branch
      - name: Push new files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.TokenForWorkflow }}  # Use your custom token
